// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsSpn23Bt1jzhj8SR0DHFkWnewh0ngTfA',
    appId: '1:797865293026:web:7309071a6a792db33e5abb',
    messagingSenderId: '797865293026',
    projectId: 'children-d0401',
    authDomain: 'children-d0401.firebaseapp.com',
    databaseURL: 'https://children-d0401-default-rtdb.firebaseio.com',
    storageBucket: 'children-d0401.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXZhLGgG9N8dxhIkEcJGuhd-paOoIFt8M',
    appId: '1:797865293026:android:5224386cf569f9913e5abb',
    messagingSenderId: '797865293026',
    projectId: 'children-d0401',
    databaseURL: 'https://children-d0401-default-rtdb.firebaseio.com',
    storageBucket: 'children-d0401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoZbaD_dhfT5dGBvRQDxYGSybd9JZkfY0',
    appId: '1:797865293026:ios:2d89d10cd28c2ea63e5abb',
    messagingSenderId: '797865293026',
    projectId: 'children-d0401',
    databaseURL: 'https://children-d0401-default-rtdb.firebaseio.com',
    storageBucket: 'children-d0401.firebasestorage.app',
    iosBundleId: 'com.example.heartGuardian',
  );

}